# Generated by Django 5.2 on 2025-05-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_person_options_remove_person_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yellow_cards',
        ),
    ]
