# Generated by Django 5.2 on 2025-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_player_red_cards_remove_player_yellow_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter a brief bio or profile of this person', verbose_name='Biography'),
        ),
    ]
